### PR TITLE
Get the correct socket infor in case of ipv6.

### PR DESCRIPTION
**Pull request by dmanchon**

### CODE REVIEW

**Comment by technige** [comment]
That was quick, thank you :-)

My thoughts on the code:
1. We should probably wrap this up into a small helper function to reduce duplication: `get_host_port(socket) -> host, port`.
2. Explicit checks on `AF_INET`, rather than a simple `else` would ensure this can't happen again. If the address family isn't recognised at all, we should raise a `ProtocolError`.
3. Tests.

Have you signed our [CLA](https://neo4j.com/developer/cla/)? I'm happy to work on this otherwise.

**Comment by dmanchon** [comment]
Agree with all. I still didnt figure out yet how correctly run the tests.

Thanks.

**Comment by technige** [comment]
`./runtests.sh` should do it though you'll need to `pip install boltkit -r test/requirements.txt` first.

**Comment by dmanchon** [comment]
Thanks. I just agreed the CLA and i the tests passed in my local machine but unfortunately they are failing in the CI

**Comment by technige** [comment]
Closing this PR as this has now been added in https://github.com/neo4j/neo4j-python-driver/commit/6c5f6fb2e67c57ebdcb520e3ced38e180c476229

**Pull request closed without merging**
