### PR TITLE
Add scripts for building conda package and deployingn to anaconda.org

### PR DESCRIPTION
**Pull request by joshbtn**
Great project thanks for sharing!

This pull request contains scripts I used to package your project with conda and deploy it to anaconda.org (https://anaconda.org/joshbtn/neo4j-driver).  The upload location is driven by the anaconda token.

I leveraged TravisCI to deploy based on a new tag being created. The only thing that needs to be set in travis to make this work is an ANACONDA_TOKEN.

Regards,
Josh Bennett

### CODE REVIEW

**Comment by technige** [comment]
Thanks. We'll look into this.

**Comment by technige** [comment]
Hi @joshbtn 

I've just started looking at this but I'm unfamiliar with Anaconda in general. Could you help me understand how this benefits users above and beyond the PyPI distribution, and how this might be achieved through our own internal build infrastructure, rather than Travis CI.

Thanks
Nigel

**Comment by jberends** [comment]
> Hi @joshbtn
> 
> I've just started looking at this but I'm unfamiliar with Anaconda in general. Could you help me understand how this benefits users above and beyond the PyPI distribution, and how this might be achieved through our own internal build infrastructure, rather than Travis CI.
> 
> Thanks
> Nigel

Anaconda is similar to PyPI in the way you distribute, however a lot of (my) corporate clients may only use anaconda repositories for download of packages and not from PyPI due to their internal IT regulations which are overly concerned with security. Therefore it would be beneficial to have all neo4j packages distributed both in PyPI and in Anaconda. This contributes to the bottomline of adoption of neo4j in python (which is the de-facto (and discussable) standard for datascience and AI projects)

**Comment by martin-neotech** [comment]
I will have a look into this for the 4.0 release of the driver.

**Comment by robsdedude** [comment]
I don't think this is needed any longer as conda forge picked up the slack :raised_hands: :bow: 

https://github.com/conda-forge/neo4j-python-driver-feedstock

**Pull request closed without merging**
