### PR TITLE
Fix docstring example: session.begin_transaction() needs to be awaited

### PR DESCRIPTION
**Pull request by 112358fn**
Found this error in the docstring while working with the async module of the driver. When the `session` is an instance of `AsyncSession` the method begin_transaction() is async and needs to be awaited. The example in the docstring was missing the `await` keyword and running it as that returns `AttributeError: __aenter__`

### CODE REVIEW

**Comment by robsdedude** [comment]
Hello and thanks for taking the time to fix the docstring and opening this PR. Before I can even review it, I must ask you to sign our [CLA (Contributor License Agreement)](https://neo4j.com/developer/cla/).

**Comment by 112358fn** [comment]
Sure! I just did it, sorry for the delay. It is a great module by the way: very clean and well documented! I just felt that a little detail like that fix can save someone some time. Thank you for taking the time to review it.

**Comment by robsdedude** [comment]
Perfect. Thanks for the kind words and taking the time to contribute to our library! :raised_hands:

**Review by robsdedude — APPROVED** [review]
:books: :hourglass_flowing_sand:

**Pull request merged**
