### PR TITLE
Refactor Logging Hierarchy in neo4j-python-driver

### PR DESCRIPTION
**Pull request by OliverFarren**
This PR includes a refactor of the logger names in the neo4j-python-driver to adhere to a hierarchical structure. 

Moving to hierarchical loggers is a non-breaking changed designed to offer more control when managing logs and provides a mechanism for better organisation and filtering of logs. 

``` python
import logging

logger = logging.getLogger("neo4j.async.io")
logger.setLevel(logging.CRITICAL)
```

### CODE REVIEW

**Comment by robsdedude** [comment]
Thank you for taking the time to craft a PR. Much appreciated.

However, before I can review the code itself, please sign the [CLA (Contributor License Agreement)](https://neo4j.com/developer/cla/).

General feedback from the PR description: I like the idea. However, I'd not want to leak the internal module structure. Instead, I'd prefer a logical hierarchy.

Something along the lines of
 * `neo4j`
   * `.network` (socket related logging)
   * `.bolt` (protocol messages)
   * `.pool` (connection pooling, and probably also routing as those two concepts are inherently coupled)
   * possibly more?

**Comment by OliverFarren** [comment]
> Thank you for taking the time to craft a PR. Much appreciated.
> 
> However, before I can review the code itself, please sign the [CLA (Contributor License Agreement)](https://neo4j.com/developer/cla/).
> 
> General feedback from the PR description: I like the idea. However, I'd not want to leak the internal module structure. Instead, I'd prefer a logical hierarchy.
> 
> Something along the lines of
> 
> * `neo4j`
>   
>   * `.network` (socket related logging)
>   * `.bolt` (protocol messages)
>   * `.pool` (connection pooling, and probably also routing as those two concepts are inherently coupled)
>   * possibly more?

Hi @robsdedude, i've signed the CLA

That sounds good to me, so to clarify, you'd avoid the sync/async split?

**Comment by OliverFarren** [comment]
@robsdedude, i've consolidated the logger hierarchy, let me know your thoughts. database drivers are a bit outside my technical area so I don't have any input into the logical splitting.

**Comment by robsdedude** [comment]
Thanks again for the update. I went through the PR and adjusted it a little:
 * add API docs
 * merged `network` and `bolt` loggers back into one `io` logger (sorry for the extra work :grimacing:). Going over the code, I found it's really hard to draw a line between raw IO (there's not much being logged there) and the bolt protocol.
 
 Please have a look at the PR and let me know if it still looks good to you.

**Review by OliverFarren — COMMENTED** [review]
Hi I think this is good. 

Thanks for adding the documentation. I still wonder whether there could be more granularity, but having looked through how the loggers are used in the different module i'm not sure. 

If you have any thoughts i'd be interested in hearing them otherwise I think this is good

**Comment by OliverFarren** [comment]
@robsdedude could we get it merged in?

**Review by robsdedude — APPROVED** [review]
:scroll:

**Pull request merged**
